export const BASE_STYLE_VALUE = {
  position: 'static',
  width: 'Auto',
  height: 'Auto',
  fontFamily: 'Arial',
  fontSize: 14,
  fontWeight: 'normal',
  fontStyle: 'normal',
  textDecoration: 'none',
  textAlign: 'left',
  lineHeight: 1.5,
  letterSpacing: 0,
  color: 'rgba(0, 0, 0, 1)',
  backgroundColor: 'rgba(0, 0, 0, 0)',
  border: 'none',
  borderRadius: 0,
  boxShadow: 'none',
  opacity: 1,
  zIndex: 0,
  overflow: 'visible',
  cursor: 'default',
  transform: 'none',
  transition: 'none',
  animation: 'none',
  display: 'block',
  float: 'none',
  clear: 'none',
  verticalAlign: 'baseline',
  whiteSpace: 'normal',
  wordBreak: 'normal',
  wordWrap: 'normal',
  content: 'none',
  visibility: 'visible',
  positionType: 'relative',
  top: 0,
  right: 0,
  bottom: 0,
  left: 0,
  widthType: 'fixed',
  widthUnit: 'px',
  heightType: 'fixed',
  heightUnit: 'px',
};