
export const pages:any = [
    {
      F_PAGE_ID: "o1y4SbElHUjRlDQmW5uXQB",
      F_TITLE: "111",
      F_P_ID: "3Mcd8RV2SpDtPdFBz0iwsn",
      F_STYLE: null,
      F_PT_ID: null,
      F_WIDTH: null,
      F_HEIGHT: null,
      IS_GROUP: false,
      F_ORDER: 21040,
      F_TYPE: null,
      F_ACCESS_USERS: null,
      PAGES: null,
      F_CONTENT: null,
    },
    {
      F_PAGE_ID: "EfjnEVWWTW2MPRVzLSh6PD",
      F_TITLE: "222",
      F_P_ID: "3Mcd8RV2SpDtPdFBz0iwsn",
      F_STYLE: null,
      F_PT_ID: null,
      F_WIDTH: null,
      F_HEIGHT: null,
      IS_GROUP: false,
      F_ORDER: 21041,
      F_TYPE: null,
      F_ACCESS_USERS: null,
      PAGES: null,
      F_CONTENT: null,
    },
    {
      F_PAGE_ID: "9hlzoE858yK2P5W_ejvRRi",
      F_TITLE: "333",
      F_P_ID: "3Mcd8RV2SpDtPdFBz0iwsn",
      F_STYLE: null,
      F_PT_ID: null,
      F_WIDTH: null,
      F_HEIGHT: null,
      IS_GROUP: false,
      F_ORDER: 21042,
      F_TYPE: null,
      F_ACCESS_USERS: null,
      PAGES: null,
      F_CONTENT: null,
    },
    {
      F_PAGE_ID: "z_QxthQXHR7qff6EWvRz2U",
      F_TITLE: "444",
      F_P_ID: "3Mcd8RV2SpDtPdFBz0iwsn",
      F_STYLE: null,
      F_PT_ID: null,
      F_WIDTH: null,
      F_HEIGHT: null,
      IS_GROUP: false,
      F_ORDER: 21043,
      F_TYPE: null,
      F_ACCESS_USERS: null,
      PAGES: null,
      F_CONTENT: null,
    },
]